-- FORMA: базова схема Supabase
-- Безпечний для повторного запуску: таблиця створюється, якщо її ще немає.
-- НЕ вставляй сюди secret/service_role key.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price integer not null default 0,
  image text,
  memory text,
  color text,
  condition text,
  battery text,
  warranty text,
  cpu text,
  gpu text,
  ram text,
  storage text,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Публічне читання каталогу.
drop policy if exists "Products are publicly readable" on public.products;
create policy "Products are publicly readable"
on public.products
for select
to anon, authenticated
using (true);

-- Адміни
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Адміністратор може бачити лише свій запис у списку адмінів.
drop policy if exists "Admins can view own admin record" on public.admin_users;
create policy "Admins can view own admin record"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

-- ВАЖЛИВО: перед запуском заміни email@example.com на email твого Auth-користувача.
insert into public.admin_users (user_id)
select id
from auth.users
where email = 'email@example.com'
on conflict (user_id) do nothing;

-- Тільки адміни можуть додавати/змінювати/видаляти товари.
drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
)
with check (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

select count(*) as admin_count from public.admin_users;
